# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('photoId', models.CharField(max_length=30)),
                ('photoUrl', models.CharField(max_length=200)),
                ('buyLink', models.CharField(default=b'https://www.amazon.com', max_length=200)),
            ],
        ),
    ]
