# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photorecord',
            name='brand',
            field=models.CharField(default=b'Unknown', max_length=100),
        ),
    ]
