# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0002_photorecord_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photorecord',
            name='buyLink',
            field=models.CharField(default=b'https://www.amazon.com', max_length=1000),
        ),
        migrations.AlterField(
            model_name='photorecord',
            name='photoId',
            field=models.CharField(max_length=100),
        ),
    ]
