# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-04 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0003_auto_20160407_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='photorecord',
            name='x',
            field=models.FloatField(default=5.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photorecord',
            name='y',
            field=models.FloatField(default=5.0),
            preserve_default=False,
        ),
    ]
