# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_upload', '0004_auto_20160504_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='photorecord',
            name='gender',
            field=models.CharField(default=b'Female', max_length=100),
        ),
        migrations.AddField(
            model_name='photorecord',
            name='height',
            field=models.FloatField(default=175),
        ),
        migrations.AddField(
            model_name='photorecord',
            name='shape',
            field=models.CharField(default=b'Banana', max_length=100),
        ),
        migrations.AddField(
            model_name='photorecord',
            name='weight',
            field=models.FloatField(default=70),
        ),
    ]
