# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitu_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bodyShape',
            field=models.CharField(choices=[('Pear', 'Pear'), ('Apple', 'Apple'), ('Banana', 'Banana')], default=b'Pear', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default=b'male', max_length=10),
        ),
    ]
