# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitu_backend', '0002_auto_20160406_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default=b'Male', max_length=10),
        ),
    ]
