# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitu_backend', '0003_auto_20160406_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatarUrl',
            field=models.CharField(default=b'https://s3.amazonaws.com/fituuseravatar/default.jpg', max_length=500),
        ),
    ]
