# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitu_backend', '0004_customuser_avatarurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='height',
            field=models.FloatField(default=5.5),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='weight',
            field=models.FloatField(default=150),
        ),
    ]
