# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-05 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitu_backend', '0007_auto_20160413_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bodyShape',
            field=models.CharField(default=b'Male_1', max_length=20),
        ),
    ]
